# This is a basic workflow to help you get started with Actions

name: Push Image to Azure

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ test/ci ]
  #  pull_request:
  #    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: cd
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: openhack3mg4iju8acr.azurecr.io
          repository: openhack2021/v1
          tag_with_ref: true
          dockerfile: ./apis/trips/Dockerfile
          path: apis/trips

  deploy:
    needs : [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: publish the image on stage env
        uses: azure/webapps-deploy@v2
        with:
          publish-profile: ${{ secrets.STAGE_AZURE_CREDENTIALS }}
          app-name: 'openhack3mg4iju8tripviewer'
          images: 'openhack3mg4iju8acr.azurecr.io/openhack2021/v1'
          slot-name: openhack3mg4iju8tripviewer-stage

      - id: stage_healthcheck
        name: Validate Stage Healthcheck
        run: |
          status=$(curl -sS "https://openhack3mg4iju8tripviewer-openhack3mg4iju8tripviewer-stage.azurewebsites.net/api/healthcheck/trips" | jq .status)

          echo "${status}"
          echo "::set-output name=STATUS::${status}"

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Promote Deployment - Swap Stage with Production
        uses: azure/CLI@v1
        if: steps.stage_healthcheck.outputs.STATUS == '"healthy"'
        with:
          azcliversion: 2.18.0
          inlineScript: |
            az webapp deployment slot swap \
              -g openhack3mg4iju8rg \
              -n openhack3mg4iju8tripviewer \
              --slot openhack3mg4iju8tripviewer-stage \
              --target-slot production

      - id: prod_healthcheck
        name: Validate Production Healthcheck
        run: |
          status=$(curl -sS "http://openhack3mg4iju8tripviewer.azurewebsites.net/api/healthcheck/trips" | jq .status)
          echo "${status}"
          echo "::set-output name=STATUS::${status}"

      - name: Rollback Deployment - Swap Production with Stage
        uses: azure/CLI@v1
        if: steps.prod_healthcheck.outputs.STATUS != '"healthy"'
        with:
          azcliversion: 2.18.0
          inlineScript: |
            az webapp deployment slot swap \
              -g openhack3mg4iju8rg \
              -n openhack3mg4iju8tripviewer \
              --slot openhack3mg4iju8tripviewer-stage \
              --target-slot production
