# This is a basic workflow to help you get started with Actions

name: Push Image to Azure

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ test/ci ]
  #  pull_request:
  #    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: cd
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: openhack3mg4iju8acr.azurecr.io
          repository: openhack2021/v1
          tag_with_ref: true
          dockerfile: ./apis/trips/Dockerfile
          path: apis/trips
      
      - name: publish the image
        with:
          publish-profile: ${{ secrets.PUBLISH_PROFILE_OPENHACK }}
          app-name: 'openhack3mg4iju8userjava'
          images: 'openhack3mg4iju8acr.azurecr.io/madhuresh/trips-go:${{ github.sha }}' 
