name: .NET

on: [push]
env:
  AZURE_WEBAPP_NAME: 'openhack3mg4iju8poi'
  AZURE_WEBAPP_PACKAGE_PATH: 'apis/poi'      # set this to the path to your web app project, defaults to the repository root

jobs:
  package:
    name: Push Docker image 
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push 
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}   
          registry: openhack3mg4iju8acr.azurecr.io
          repository: apis/poi
          tag_with_ref: true
          dockerfile: ./apis/poi/web/Dockerfile
          path: apis/poi/web
      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'openhack3mg4iju8poi'    
          publish-profile: ${{ secrets.POI_PUBLISH_PROFILE }}
          package: 'apis/poi'

   
